default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: abujani

test:
  <<: *default
  database: abujani

production:
  <<: *default
  database: abujani
  password: mayhem


